from django.conf.urls.defaults import patterns,url

urlpatterns=patterns('quiniela.apps.champions.views',
                     url(r'^$','index_view',name='vista_principal'),
                     url(r'^respuesta/$','carga_view',name='vista_respuesta'),
                     url(r'^cargar/$','carga_view',name='vista_carga'),
                     url(r'^cargar2/$','carga2_view',name='vista_carga2'),
                     url(r'^cargar3/$','carga3_view',name='vista_carga3'),
                     url(r'^grupos/page/(?P<pagina>.*)/$','VistaGrupos_view',name='vista_grupos'),
                     url(r'^grupos2/$','VistaGrupos2_view',name='vista_grupos2'),           
                     url(r'^puntaje/$','ActualizarPuntos_view',name='vista_puntaje'),
                     url(r'^puntaje8/$','ActualizarPuntos8_view',name='vista_puntaje8'),
                     url(r'^puntaje4/$','ActualizarPuntos4_view',name='vista_puntaje4'),
                     url(r'^puntaje2/$','ActualizarPuntos2_view',name='vista_puntaje2'),
                     url(r'^puntaje1/$','ActualizarPuntos1_view',name='vista_puntaje1'),
                     url(r'^equipoF/(?P<nombreClub>.*)/$','VistaJuegos_view',name='vista_Juegos'),
                     url(r'^vistaCarga/$','vistaCarga_view',name='vista_Carga'),
                     url(r'^vistaPuntos/$','vistaPuntos_view',name='vista_Puntos'),
                     url(r'^vistaQuinielas/$','vistaQuinielas_view',name='vista_Quinielas'),
                     url(r'^menuCale/$','menuCalendario_view',name='vista_Menucale'),
                     url(r'^VercalendarioF/$','VistaCalendarioF_view',name='vista_VercalendarioF'),
                     url(r'^VercalendarioOctavos/$','VistaCalendarioOctavos_view',name='vista_VercalendarioOctavos'),
                     url(r'^VercalendarioCuartos/$','VistaCalendarioCuartos_view',name='vista_VercalendarioCuartos'),
                     url(r'^VercalendarioSemi/$','VistaCalendarioSemi_view',name='vista_VercalendarioSemi'),
                     url(r'^VercalendarioFinal/$','VistaCalendarioFinal_view',name='vista_VercalendarioFinal'),
                     url(r'^Instrucciones/$','Instrucciones_view',name='vista_Instrucciones'),
                     )